### PR TITLE
Proposed API standards updates

### PR DESCRIPTION
**Pull request by artzte**
http://developer.avalara.com/api-documentation/api-reference-template?url=https://raw.githubusercontent.com/artzte/Swagger/61065dc604615d2fb2058adebd0ee8de0f9d9f7f/avatax15/v2proposal.yaml

### CODE REVIEW

**Comment by markb-avalara** [comment]
"Attributes common across resource areas shall be named identically" Generally agree but in some cases (e.g. docCode) we may still want the resource prefix.

**Comment by artzte** [comment]
Yes, I agree - if an attribute's conversational reference is e.g. "docCode" or "document code" i.e. it has special meaning, then it should be named that. Same with e.g. "company code". But e.g. "name" or "id" or "description" would be named generically.

**Comment by davidlottavalara** [comment]
Do we need a messageId so people don't rely on hardcoded message text?

There should probably be an explicit list of these exceptions.

**Comment by markb-avalara** [comment]
I agree on the need for messageIds. Something like "CompanyNotFound" rather than a number though.

**Comment by anyarms** [comment]
Changes to the standards (or clarifications to the standards) should be maintained in confluence.

**Pull request closed without merging**
